### ISSUE TITLE
feat: move to settings panel field on preview click

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp-campaigns#108]
# Feature Request

## User Story

As an admin, I want to click on an area in the campaign preview and be taken to that field in the settings panel so that I can quickly make changes and not have to look for the setting.

## Possible Solution

When the user clicks on specific fields on the preview, they should be taken to that field in the settings panel and that field should be in focus. There should be some indicator that the field will take them to the settings panel (a floating icon or something similar). If that area is collapsed it should be expanded. This should be done initially on the `Introduction` settings, but the approach taken needs to support other settings panels. 

## Related

https://give.productboard.com/feature-board/879919-givewp-feature-hierarchy/features/3105263/detail

## Acceptance Criteria

- [x] The field is indicated as "editable"
- [x] Clicking on the field takes you to the proper setting field
- [x] Setting field does not lose its value when going into edit
- [ ] If collapsed, the field should be made visible.

**Comment by ravinderk** [comment]
@knowler I did not work on this point because I did not find a quick fix.
```
 If collapsed, the field should be made visible.
```
