### ISSUE TITLE
feat: Add Go Live to navigation

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp-campaigns#109]
# Feature Request

## User Story

As an admin, I want to see the `Go Live` in the left hand navigation so that I know I can make a campaign live after changing settings. 

## Visuals

![image](https://user-images.githubusercontent.com/1054196/66875820-3cb1ad00-ef75-11e9-923d-792088c29743.png)

## Possible Solution

`Go Live` needs to be added to the left hand navigation, but does not need to take the campaign live (future Issue)

## Acceptance Criteria

- [ ] `Go Live` appears in the left hand navigation

**Comment by ravinderk** [comment]
@mikejhale As I can see, it is already there. Let me know if I am missing something.

![image](https://user-images.githubusercontent.com/1784821/66893815-92856400-f00c-11e9-8540-d90917276d46.png)
