### ISSUE TITLE
fix: remove gwp- prefix from tailwind classes

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp-campaigns#113]
# Bug Report

## Developer Story
I find that after resolving #95  few tailwind `gwp-` still left.

## Possible Solution
Remove all `gwp-` prefix from tailwind classes.

## Acceptance Criteria
- [x] All used tailwind class does not have `gwp-` prefix

**Comment by knowler** [comment]
I had intentionally left the prefix on component classes. See my reasoning for that here: https://github.com/impress-org/givewp-campaigns/pull/105#discussion_r335194711

**Comment by ravinderk** [comment]
@knowler I was talking about other classes, check this pr: https://github.com/impress-org/givewp-campaigns/pull/114/files
