### ISSUE TITLE
fix: unable to scroll on setting content

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp-campaigns#115]
# Bug Report

## Developer Story
As a developer, I want the admin to get access to all settings by scrolling vertically which does not show on the current screen.

![image](https://user-images.githubusercontent.com/1784821/66909157-e81c3980-f029-11e9-83a5-7af08762dee0.png)

## Current Behavior
I can not scroll on the setting.

## Related to
#95 

## Acceptance Criteria
- [ ] I am able to scroll on campaign setting to view all settings when all setting section opened.

**Comment by knowler** [comment]
I have this fixed (with just flexbox still — no absolute positioning hacks). I did it in a fresh HTML page just so I could get my head around it a little better:

![flex-scroll](https://user-images.githubusercontent.com/6908001/67052695-28e48300-f0fc-11e9-9e57-e4c77da610d4.gif)

**Preview**: https://gelatinous-radish.glitch.me/
**Code**: https://glitch.com/edit/#!/gelatinous-radish

I’m implementing this into the app now.

**Comment by DevinWalker** [comment]
@knowler that's awesome! ... And a happy cat to boot!
