### ISSUE TITLE
chore: separate builder and campaign components

### ISSUE THREAD

**Issue by knowler** [impress-org/givewp-campaigns#131]
Separate [campaign builder components](https://www.figma.com/file/jaVXDA4wjQD9OqTi0l9KQe/GiveWP-Campaigns?node-id=132%3A6) from [campaign components](https://www.figma.com/file/jaVXDA4wjQD9OqTi0l9KQe/GiveWP-Campaigns?node-id=0%3A335). In Figma, there is a clear distinction between the two which we need to reflect here as well. We might be able to extract some primitives that can be the basis of both sets of components.

**Comment by DevinWalker** [comment]
Closing as there's lots of work going on here that @knowler reviewed with me today.
