### ISSUE TITLE
refactor: use progress tag in ProgressBar component

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp-campaigns#152]
# Feature Request

## Developer Story
As a developer, I want to use the latest HTML5 `progress` tag  in the `ProgressBar` component.

component: https://github.com/impress-org/givewp-campaigns/tree/develop/resources/js/components/progressbar

doc:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress
https://css-tricks.com/html5-progress-element/

## Acceptance Criteria
- [ ] We are using `progress` tag in `ProgressBar` component.
- [ ] `ProgressBar` looks same on broswer with support HTML5 or viceversa

**Comment by ravinderk** [comment]
@knowler I tried to use `progress` tag but I found that there will be cross-browser challenges with that as mentioned in the post: https://css-tricks.com/html5-progress-element/

Let me know if we can close this issue or you can take over it.

**Comment by DevinWalker** [comment]
Let's not get too fancy for sake of using stuff. Let's just use what works now and is cross-browser compatible as much as possible. Closing.
