### ISSUE TITLE
fix: use current colorPicker hover color in preview

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp-campaigns#155]
# Bug Report

## User Story

As a user, I want to see the current color on the preview so that I can see how it will look.

## Current Behaviour

On hover, the color picker is updating the preview with the previous hover color, not the current one. 

## Expected Behaviour

Preview will reflect the current color I'm hovering over

## Steps to Reproduce

1. Hover over a color on the color picker
2. Hover to another color
3. Observe the color in the preview is the first color

## Visuals

https://www.loom.com/share/de7f3e2986e54b85928a8da058235efc

## Acceptance Criteria

- [x] Preview shows the current hover color
- [x] Campaign: Progress Bar Color
- [x] Design:  Primary Color
- [x] Design: Background Color

**Comment by ravinderk** [comment]
fixed: https://github.com/impress-org/givewp-campaigns/commit/dd23a59140d475b2d5baa7c6c5a9d3c6c6acb778
