### ISSUE TITLE
fix: increase size of check icon on Thank You page

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp-campaigns#162]
# Bug Report

## User Story

As a donor, I want to see a checkmark confirmation so that I know my donation was successful.

## Current Behaviour

Campaign > Thank You (page) > Preview: Check icon is too small

## Expected Behaviour

Icon is properly sized

## Visuals

![image](https://user-images.githubusercontent.com/1054196/67786017-2bb86f80-fa3c-11e9-9303-fb79263affb3.png)

## Acceptance Criteria

- [ ] Icon is properly sized

**Comment by knowler** [comment]
@mikejhale Can you send me a [My Browser report](https://mybrowser.fyi/)? Also, is this a production build (`yarn prod`) or a development build (`yarn dev`). Currently, using [Chrome 77 macOS 10.14.5](https://mybrowser.fyi/report/5db865a6f6c8c70015b2a928) this displays fine, so I suspect it’s just a cross platform issue.

**Comment by mikejhale** [comment]
@knowler 

https://mybrowser.fyi/report/5db9c10995caf400158d7ddd

**Comment by DevinWalker** [comment]
Done
