### ISSUE TITLE
feat: campaign editor settings sidebar

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp-campaigns#17]
# Feature Request

## User Story

As an admin, I want a centralized location for editing settings so that I can build campaigns efficiently.

## Visuals
https://drive.google.com/open?id=1lsI_WRmOiKiS0VIcxmb5f-rgRA2VCVGQ

## Possible Solution
The settings sidebar should be a grouping of settings panels that allows a user to expand and contract a settings panel. The sidebar will vary depending on the campaign step being edited so panels should be able to be passed in as a collection. 

This is for creating the settings sidebar itself with expandable sections. 

## Acceptance Criteria

- [x] Settings sidebar appears on the page
- [x] Sections can be expanded and collapsed
- [x] Section panel components can be passed in to the sidebar.

**Comment by ravinderk** [comment]
Discussion: https://givewp.slack.com/archives/C0FAGC83C/p1569948178250700
