### ISSUE TITLE
chore: investigate replacing npm with yarn

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp-campaigns#2]
## User Story
As a developer, I want to use Yarn to manage dependencies so that the build process is more efficient and faster. 

## Possible Solution
Look at how GiveIO uses Yarn

## Related

**Comment by ravinderk** [comment]
@mikejhale Let use `yarn` for now if we will see any requirement of `npm` then we will switch.
ref: https://github.com/impress-org/givewp-campaigns/pull/9
