### ISSUE TITLE
feat: match current page selector background color with figma

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp-campaigns#207]
# Feature Request

## Developer Story
As a developer, I want current page selector background color to look the same as in Figma

## Visuals
![image](https://user-images.githubusercontent.com/1784821/68879448-6f46f500-072f-11ea-85a2-531728c1079c.png)

## Possible Solution
Update background-color

## Acceptance Criteria
- [ ] Background color of current [age selector same as Figma.

**Comment by DevinWalker** [comment]
Uber simple one for you here @henryholtgeerts
