### ISSUE TITLE
fix: match CampaignPageSelector component design 

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp-campaigns#218]
# Bug Report

## developer Story
As a developer, I want to see the same design of the `CampaignPageSelector` component as in `Figma`.

![image](https://user-images.githubusercontent.com/1784821/69168989-9d587a80-0b1d-11ea-96c9-e8c6f15110f8.png)

## Current Behaviour
I can notice an issue with font-weight, background color, and space between static text and options.

## Expected Behaviour
The design should match.

## Bug Type
- [x] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Acceptance Criteria
- [x] CampaignPageSelector style match with design in `Figma`

**Comment by knowler** [comment]
This was resolved in #243
