### ISSUE TITLE
feat: step options settings panel

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp-campaigns#22]
# Feature Request

## User Story

As an admin, I want manage campaign give settings so that I can easily and visually create a campaign.

## Visuals

https://drive.google.com/open?id=1lsI_WRmOiKiS0VIcxmb5f-rgRA2VCVGQ

## Possible Solution

Step options settings should include: 
- Header text
- Next Button Text
- Previous Button Text

The step options panel should be aware when there is a previous/next step and show previous/next accordingly. 

## Related

feat: campaign editor settings sidebar #17 

## Acceptance Criteria

- [ ] Panel contains the settings listed above
- [ ] Panel can be included in the settings sidebar
- [ ] Panel settings changes are reflected in the preview

**Comment by DevinWalker** [comment]
Closing as this is not MVP and we need to provide more detail in a concept to get this done. When we tackle this it will be an epic and design will be part of it. We do already have wireframes for the feature.
