### ISSUE TITLE
research: how we can reuse stripe core and stripe premium code in donation payment process and after?

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp-campaigns#234]
## Research Description
Answer the following questions:

**Stripe Core**
- With react can we use credit card process code
- With react can we reuse code and perform donation with Strip Checkout
-  Can we reuse webhook handler code

Stripe Premium
- Can we reuse follow payment method
   - Google Pay 
   - Apple Pay 
   - Stripe + Plaid
   - Stripe Checkout
   - Stripe iDEAL

**Comment by ravinderk** [comment]
### Report
I reviewed the Stripe payment gateway related code in Give core and premium add-on to check the probability of code reusability.
**I found that javascript and PHP code ( exclude few classes ) is tightly coupled.**

Few points from a code perspective:
- Javascript is tightly coupled to the donation form
   - https://github.com/impress-org/givewp/blob/develop/assets/src/js/frontend/give-stripe.js
   - https://github.com/impress-org/givewp/blob/develop/assets/src/js/frontend/give-stripe-checkout.js
- We are using donation form hooks to render custom output like notices and custom field which play an important role in donation processing.
   - https://github.com/impress-org/givewp/tree/develop/includes/gateways/stripe/includes

### Suggestion:
Considering a few points for campaign form:
1. form will render in an iframe.
2. form will have a new form data object.

We can process donation with the campaign form if we implement the following thing:
1. Rewrite javascript code for a form with React ( using [Stripe react element](https://github.com/stripe/react-stripe-elements) )
2. Develope a data modifier which translates campaign form data into Give core compatible data (before donation processing start).
     The Data Modifier will hijack `$_POST` to setup values because most of the place our code access forms data from this constant to process the donation.
     We can discuss why and how, but Data Modifier will make easy to make existing add-ons code to compatible with campaigns.
3. Handle conditional logic like Zero-based currency in new campaign javascript code, which depends upon DOM architecture.

**Comment by ravinderk** [comment]
@JasonTheAdams Here is an explanation of donation processing in Give core and how logic tightly coupled to `$_POST`:
1. Donation processing start from `give_purchase ` action hook: https://github.com/impress-org/givewp/blob/1dcce4773b978f8d694fddde219ea0c6d289652f/includes/process-donation.php#L210
      1. As you can see at the beginning of the function `give_process_donation_form ` we sanitize `$_POST` data and creating a new variable `$post_data ` which we are using in function. In this function, you will see a lot of logic perform on the basis of post variable.
      2.  At the end of this function, you will see another action hook to which we are passing `$donation_data` which contain `$post_data` in `post_data` key which we will use by the payment gateway and other add-ons to process donation:
https://github.com/impress-org/givewp/blob/1dcce4773b978f8d694fddde219ea0c6d289652f/includes/process-donation.php#L206
https://github.com/impress-org/givewp/blob/1dcce4773b978f8d694fddde219ea0c6d289652f/includes/process-donation.php#L160

If you will search add-ons code then you will find that lots of add-ons are using this:
**Give Core** (including Stripe Core )
![image](https://user-images.githubusercontent.com/1784821/69570642-34be4180-0fe6-11ea-9d66-c6f37b2a4069.png)

**Stripe Premium**
![image](https://user-images.githubusercontent.com/1784821/69570695-53bcd380-0fe6-11ea-9817-d94786ee7331.png)

**Recurring**
![image](https://user-images.githubusercontent.com/1784821/69570569-15bfaf80-0fe6-11ea-97c2-a3eab4a44556.png)

**Fee Recovery**
Note: I did not find usage of `post_data` in fee recovery but we can see that this add-on accessing data from `$_POST` and the same for others.
![image](https://user-images.githubusercontent.com/1784821/69570824-a9917b80-0fe6-11ea-81ec-e2c7a8b54c81.png)
