### ISSUE TITLE
research: how we can reuse recurring addon code in donation payment process and after?

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp-campaigns#241]
## Research Description
- Can we set up a recurring donation by campaign builder setting ( consider support only for Stripe )

**Comment by ravinderk** [comment]
**Report**
As I mentioned in https://github.com/impress-org/givewp-campaigns/issues/234#issuecomment-558113969 comment, most of the statement also applies for each Give add-on. Most of the code is tightly coupled with form data (submitted from frontend) to create a recurring donation.

You can see this code sample:
https://github.com/impress-org/give-recurring/blob/adc5f4f63cb574e16d87a244e2db15645db7633c/give-recurring.php#L1141

If we want to use currently recurring functionality then we have feed data in the required structure.

**Comment by DevinWalker** [comment]
Closing because the research tells us we will need to recreate a lot of the same functionality already within our codebase (using jQuery and other client-side code). Potentially some of the server-side code could work but it's still not certain whether we want to go that route.
