### ISSUE TITLE
feat: campaign design settings panel

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp-campaigns#25]
# Feature Request

## User Story

As an admin, I want manage campaign design settings so that I can easily and visually create a campaign.

## Visuals

https://drive.google.com/open?id=1lsI_WRmOiKiS0VIcxmb5f-rgRA2VCVGQ

## Possible Solution

Design settings should include: 
- Font selector
- Primary color selector
- max-width

## Related

feat: campaign editor settings sidebar #17 

## Acceptance Criteria

- [ ] Panel contains the settings listed above
- [ ] Panel can be included in the settings sidebar
- [ ] Panel settings changes are reflected in the preview

**Comment by ravinderk** [comment]
@knowler I am taking over this as we discussed over dev call.
