### ISSUE TITLE
chore: investigate using Laravel Mix as a build tool

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp-campaigns#3]
## User Story
As a developer, I want to use Laravel Mix as a build tool to manage build related tasks so that project build configuration can be easy to manage. 

## Possible Solution
Look at how GiveIO uses Laravel Mix as a build tool. 

## Related

**Comment by ravinderk** [comment]
@mikejhale I review Laravel Mix and It is really helpful to speed up development. Laravel Mix API is robust to make most of the features available like `browserSync`.

Because Laravel Mix is a wrapper to WebPack, we can move anytime if feels lack of lack.
