### ISSUE TITLE
chore: determine approach and tools to maintain code formatting and standards

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp-campaigns#4]
## User Story
As a developer, I want source code to be consistent and written according to standards and best practices so that the code is more maintainable..  

## Possible Solution
- [ESLint](https://eslint.org/)
- [Prettier](https://prettier.io/)
- [Husky](https://github.com/typicode/husky)
- [PHPCS](https://github.com/squizlabs/PHP_CodeSniffer)

## Related
Look at https://github.com/matzeeable/wp-reactjs-starter for ideas of tools

**Comment by ravinderk** [comment]
Closing in favor of https://github.com/impress-org/givewp-campaigns/pull/9
