### ISSUE TITLE
chore: determine best way to handle PHP class autoloading

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp-campaigns#5]
## User Story
As a developer, I want to use PHP Namespaces and Autoloading so that the code is more maintainable. 

## Possible Solution
Using a drop-in autoloader, or PSR-4 autoloading. 

## Related
https://github.com/tommcfarlin/simple-autoloader-for-wordpress/
http://justintadlock.com/archives/2018/12/14/php-namespaces-for-wordpress-developers

**Comment by ravinderk** [comment]
@DevinWalker As suggests, I added autoload from wp business review which looks good to me.
