### ISSUE TITLE
fix: refactor style to use only tailwind styling

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp-campaigns#69]
# Feature Request

## Developer Story
As a developer, I want to see the admin template built with tailwind CSS only.>

## Acceptance Criteria
- [x] We are not using custom classes for admin header, sidebar and sidebar panel interfaces.

**Comment by DevinWalker** [comment]
Closing as this has been largely completed for the initial pass through. Additional issues will be opened for styling as needed.
