### ISSUE TITLE
feat: create workspace for utility functions

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp-campaigns#83]
# Feature Request

## Developer Story
As a developer, I want to take leverage of already built functionality.

## Possible Solution
Allow access to utility functions with `@givewp/utils` packages

## Acceptance Criteria
- [ ] I can access utility functions with `@givewp/utils`

**Comment by DevinWalker** [comment]
@knowler @ravinderk I'm looking for a status update on this issue. If this is being addressed in the large PR refactor that Nathan is working on then please update me accordingly.

**Comment by ravinderk** [comment]
@DevinWalker It is not implemented yet. @knowler will take care of this.

**Comment by DevinWalker** [comment]
Closing as part of prototype to foundation refactor.
